# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f1933a1267f8ca3588e5d9ecedc6f5604d630deef703d45f3ce6ac635cdb02099ddce58ae8b82f242c691e49ee14073cc4990da91c5fb9572a1be8582e1366e

test:
  secret_key_base: 922d186fbcbb1676731a0514203dbf17deaa5165d6b5c0fe8621910ffc21ce8eb10bb0d4042c2145dfc95b52fcfdeadf07b36889f738d1cdd8e2a8a8cd94e146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
